# Generated by Django 5.0.4 on 2024-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_featuredevents_featuredevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='featuredevent',
            name='featuredEvents',
            field=models.CharField(choices=[('TcN', 'TwitchCon, San Diego Convention Center, San Diego CA'), ('CcN', 'Comic-Con, San Diego Convention Center, San Diego CA'), ('NYc', 'New York Comic-Con, Javits Center, NYC NY'), ('SfF', 'Sundance Film Festival, Park City UT'), ('LoL', 'Lollapalooza, Grant Park, Chicago IL'), ('BmF', 'Burning Man Festival, Black Rock Desert, Nevada')], max_length=150),
        ),
    ]
