# Generated by Django 5.0.4 on 2024-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_task_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredevent',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredevent',
            name='image_url',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
