# Generated by Django 5.0.4 on 2024-04-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_featuredevent_description_featuredevent_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredevent',
            name='featuredEvents',
            field=models.CharField(choices=[('NjH', 'New Orleans Jazz Festival, Fair Grounds Race Course & Slots, New Orleans LA'), ('F1M', 'F1 Crypto.com Miami Grand Prix, Miami FL'), ('BnO', 'Bonnaroo Music Festival, Manchester TN'), ('CcN', 'Comic-Con, San Diego Convention Center, San Diego CA'), ('LoL', 'Lollapalooza, Grant Park, Chicago IL'), ('BmF', 'Burning Man Festival, Black Rock Desert, NV'), ('TcN', 'TwitchCon, San Diego Convention Center, San Diego CA'), ('NYc', 'New York Comic-Con, Javits Center, NYC NY'), ('NFR', 'National Finals Rodeo, Thomas & Mack Center, Las Vegas NV'), ('SfF', 'Sundance Film Festival, Park City UT')], max_length=150),
        ),
    ]
