# Generated by Django 5.0.4 on 2024-04-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_featuredevent_featuredevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('featured_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.featuredevent')),
            ],
        ),
    ]
