# Generated by Django 5.0.4 on 2024-04-23 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='featured_event',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
