# Generated by Django 5.0.4 on 2024-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_photo_featured_event_remove_task_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredevent',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='featuredevent',
            name='name',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='featuredevent',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
